## This script is intended to load and manipulate raw data generated by a smartphone accelerometer
## during several activities like walking, sitting, etc. and make the data tidy.

## The goal is:
## 1- Merges the training and the test sets to create one data set.
## 2- Extracts only the measurements on the mean and standard deviation for each measurement.
## 3- Uses descriptive activity names to name the activities in the data set
## 4- Appropriately labels the data set with descriptive variable names.
## 5- From the data set in step 4, creates a second, independent tidy data set with the average of each variable for each activity and each subject.

## This script assumes that the files from 
## https://d396qusza40orc.cloudfront.net/getdata%2Fprojectfiles%2FUCI%20HAR%20Dataset.zip
## are already ownloaded and unzipped in the current working directory.


library(dplyr)

## Loading Lookup Variables
setwd("UCI HAR Dataset")
features <- read.delim("features.txt", sep="", header=FALSE)
activity_labels <- read.delim("activity_labels.txt", sep="", header=FALSE)

## Load train dataset
setwd("train")
X_train <- read.delim("X_train.txt", sep="", header=FALSE, col.names=features$V2)
y_train <- read.delim("y_train.txt", sep="", header=FALSE)
subject_train <- read.delim("subject_train.txt", header=FALSE)
trainData <- mutate(X_train, Subject.id=subject_train[,1], Activity_id=y_train[,1])

## Load test dataset
setwd("../test")
X_test <- read.delim("X_test.txt", sep="", header=FALSE, col.names=features$V2)
y_test <- read.delim("y_test.txt", sep="", header=FALSE)
subject_test <- read.delim("subject_test.txt", header=FALSE)
testData <- mutate(X_test, Subject.id=subject_test[,1], Activity_id=y_test[,1])

## Merging the test and train datasets
allData <- rbind(trainData, testData)
## Joining the data with activity labels
allData <- merge(allData, activity_labels, by.x="Activity_id",by.y="V1")
names(allData)[564] <- "Activity.Name"
## Filters only columns that are mean or std values, plus subject and activity data
tidyData <- allData[c(563, 564,grep("mean[^Freq]|std",names(allData)) )]

## Rename columns
names(tidyData)[grep("^f", names(tidyData))] <- 
    sub("f", "FrequencyDomain.",names(tidyData)[grep("^f", names(tidyData))])

names(tidyData)[grep("^t", names(tidyData))] <- 
  sub("t", "TimeDomain.",names(tidyData)[grep("^t", names(tidyData))])

names(tidyData) <- sub("Acc","Acceleration.", names(tidyData))

names(tidyData) <- sub("Gyro","AngularVelocity.", names(tidyData))

names(tidyData) <- sub("BodyBody","Body", names(tidyData))

names(tidyData) <- sub("Mag","Magnitude", names(tidyData))

names(tidyData) <- gsub("\\.\\.",".", names(tidyData))
names(tidyData) <- gsub("\\.\\.",".", names(tidyData))

names(tidyData)[grep("\\.$",names(tidyData) )] <- sub("\\.$", "", names(tidyData)[grep("\\.$",names(tidyData) )])


## Grouping by subject and activity
by_activity_subject <- group_by(tidyData, Activity.Name, Subject.id)
## Calculating the mean for every column other than the ones grouped by
final_tidy_data <- summarise_each(by_activity_subject, funs(mean))

## Resetting the current working directory
setwd("../..")
## Writing the final dataset
write.table(final_tidy_data,"final_tidy_data.txt", row.names=FALSE)